__copyright__ = """
    TODO: See licences
"""

__doc__ = """Dclone AKA. Docker Clone

Usage:
    dclone run ...
    dclone image ...
    dclone build ...
    dclone start ...
    dclone stop ...
"""
